ingress:
  hosts:
    - host: awakari.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-api-tls-server
      hosts:
        - awakari.cloud
