ingress:
  hosts:
    - host: awakari.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: secret-webapp-tls-server
      hosts:
        - awakari.com

cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt
