ingress:
  hosts:
    - host: demo.awakari.cloud
      paths:
        - path: /web
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-api-tls-server
      hosts:
        - demo.awakari.cloud
