ingress:
  hosts:
    - host: awakari.com
      cookie:
        enabled: true
        name: "awakari"
        expires:
          seconds: 86400
        samesite: "Strict"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: secret-webapp-tls-server
      hosts:
        - awakari.com
