name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Release
        run: make release
